In [11]:
#Import dependencies
import pandas as pd
import scipy.stats as st
import matplotlib.pyplot as plt
from scipy.stats import linregress
import numpy as np   
from bs4 import BeautifulSoup as bs

In [12]:
#Read CSV file for 1st data source Vaccine Coverage and Exemptions among Kindergarteners
coverage_exmpt_file = "Data\Vaccination_Coverage_and_Exemptions_among_Kindergartners.csv"
coverage_exmpt_file_df = pd.read_csv(coverage_exmpt_file, encoding="ISO-8859-1")
coverage_exmpt_file_df.head(100)

,Vaccine/Exemption,Dose,Geography Type,Geography,School Year,Estimate (%),Population Size,Percent Surveyed,Footnotes,Number of Exemptions,Survey Type
0,MMR,NaN,States,Alabama,2009-10,94.0,75358.0,100.0,â¥. *. **,NaN,Census
1,MMR,NaN,States,Alaska,2009-10,NaN,9641.0,76.4,NaN,NaN,Voluntary response
2,MMR,NaN,States,Arizona,2009-10,95.0,89287.0,93.9,NaN,NaN,Census
3,MMR,NaN,States,Arkansas,2009-10,98.3,34733.0,100.0,*,NaN,Census
4,MMR,NaN,States,California,2009-10,93.6,507191.0,100.0,*,NaN,Census
...,...,...,...,...,...,...,...,...,...,...,...
95,MMR,NaN,States,South Dakota,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
96,MMR,NaN,States,Tennessee,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
97,MMR,NaN,States,Texas,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
98,MMR,NaN,National,U.S. Median,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
99,MMR,NaN,States,Utah,2010-11,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#Filter only for chickenpox vaccine (varicella)
chickenpox_df = coverage_exmpt_file_df.loc[coverage_exmpt_file_df['Vaccine/Exemption'] == 'Varicella, unknown disease history']
chickenpox_df.head(100)

,Vaccine/Exemption,Dose,Geography Type,Geography,School Year,Estimate (%),Population Size,Percent Surveyed,Footnotes,Number of Exemptions,Survey Type
1154,"Varicella, unknown disease history",1 Dose,States,Alabama,2009-10,94.0,75358.0,100.0,â¥. *. **,NaN,Census
1155,"Varicella, unknown disease history",1 Dose,States,Alaska,2009-10,NaN,9641.0,76.4,NaN,NaN,Voluntary response
1156,"Varicella, unknown disease history",1 Dose,States,Arizona,2009-10,97.5,89287.0,93.9,NaN,NaN,Census
1157,"Varicella, unknown disease history",1 Dose,States,Arkansas,2009-10,98.3,34733.0,100.0,*,NaN,Census
1158,"Varicella, unknown disease history",1 Dose,States,California,2009-10,96.6,507191.0,100.0,*,NaN,Census
...,...,...,...,...,...,...,...,...,...,...,...
1249,"Varicella, unknown disease history",1 Dose,States,South Dakota,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1250,"Varicella, unknown disease history",1 Dose,States,Tennessee,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1251,"Varicella, unknown disease history",1 Dose,States,Texas,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1252,"Varicella, unknown disease history",1 Dose,National,U.S. Median,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1253,"Varicella, unknown disease history",1 Dose,States,Utah,2010-11,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
chickepox_df_filtered_test = chickenpox_df['Survey Type'].value_counts()
chickepox_df_filtered_test

Census                                                          557
Stratified 2-stage cluster sample                                62
Voluntary response                                               47
2-stage Cluster Sample                                           36
Census (public); Voluntary response (private)                    26
Random sample                                                    22
Voluntary Response                                               15
Census (public). voluntary response (private)                    13
Not conducted                                                    12
Stratified  2-stage cluster sample                               12
Stratified 1-stage cluster sample                                 9
Convenient                                                        6
Stratified 1-stage sample  (Public);  Census (Private)            6
Not Conducted                                                     4
Simple Random Sample                                              4
Census                                                            4
Simple random sample                                              4
Census (public). Voluntary response (private)                     3
Random Sample                                                     2
Not conducted                                                     2
1-Stage Cluster Sample                                            2
Stratified 1-stage sample (Public); Census (Private)              2
Non-random Cluster Sample                                         2
1-stage stratified sample                                         2
2-stage cluster  sample                                           2
1-stage Cluster Sample                                            2
Census (Public); Stratified  2-stage cluster sample(Private)      2
Voluntary response (public); Census (private)                     2
Voluntary response (public). census (private)                     1
Name: Survey Type, dtype: int64

In [22]:
#Filter out Random Sample
chickepox_df_filtered_RS_df = chickenpox_df.loc[chickenpox_df['Survey Type'] != 'Random Sample']
chickepox_df_filtered_RS_df.head()

,Vaccine/Exemption,Dose,Geography Type,Geography,School Year,Estimate (%),Population Size,Percent Surveyed,Footnotes,Number of Exemptions,Survey Type
1154,"Varicella, unknown disease history",1 Dose,States,Alabama,2009-10,94.0,75358.0,100.0,â¥. *. **,NaN,Census
1155,"Varicella, unknown disease history",1 Dose,States,Alaska,2009-10,NaN,9641.0,76.4,NaN,NaN,Voluntary response
1156,"Varicella, unknown disease history",1 Dose,States,Arizona,2009-10,97.5,89287.0,93.9,NaN,NaN,Census
1157,"Varicella, unknown disease history",1 Dose,States,Arkansas,2009-10,98.3,34733.0,100.0,*,NaN,Census
1158,"Varicella, unknown disease history",1 Dose,States,California,2009-10,96.6,507191.0,100.0,*,NaN,Census

In [26]:
#Filter out Not Conducted Survey Types
chickepox_df_filtered_NC_df = chickepox_df_filtered_RS_df.loc[chickepox_df_filtered_RS_df['Survey Type'] != 'Not Conducted']
chickepox_df_filtered_NC_df.head(100)

,Vaccine/Exemption,Dose,Geography Type,Geography,School Year,Estimate (%),Population Size,Percent Surveyed,Footnotes,Number of Exemptions,Survey Type
1154,"Varicella, unknown disease history",1 Dose,States,Alabama,2009-10,94.0,75358.0,100.0,â¥. *. **,NaN,Census
1155,"Varicella, unknown disease history",1 Dose,States,Alaska,2009-10,NaN,9641.0,76.4,NaN,NaN,Voluntary response
1156,"Varicella, unknown disease history",1 Dose,States,Arizona,2009-10,97.5,89287.0,93.9,NaN,NaN,Census
1157,"Varicella, unknown disease history",1 Dose,States,Arkansas,2009-10,98.3,34733.0,100.0,*,NaN,Census
1158,"Varicella, unknown disease history",1 Dose,States,California,2009-10,96.6,507191.0,100.0,*,NaN,Census
...,...,...,...,...,...,...,...,...,...,...,...
1249,"Varicella, unknown disease history",1 Dose,States,South Dakota,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1250,"Varicella, unknown disease history",1 Dose,States,Tennessee,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1251,"Varicella, unknown disease history",1 Dose,States,Texas,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1252,"Varicella, unknown disease history",1 Dose,National,U.S. Median,2010-11,NaN,NaN,NaN,NaN,NaN,NaN
1253,"Varicella, unknown disease history",1 Dose,States,Utah,2010-11,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
chickepox_df_filtered_NaN_df = chickepox_df_filtered_NC_df.loc[chickepox_df_filtered_NC_df['Survey Type'] != 'NaN']
chickepox_df_filtered_NaN_df

,Vaccine/Exemption,Dose,Geography Type,Geography,School Year,Estimate (%),Population Size,Percent Surveyed,Footnotes,Number of Exemptions,Survey Type
1154,"Varicella, unknown disease history",1 Dose,States,Alabama,2009-10,94.0,75358.0,100.0,â¥. *. **,NaN,Census
1155,"Varicella, unknown disease history",1 Dose,States,Alaska,2009-10,NaN,9641.0,76.4,NaN,NaN,Voluntary response
1156,"Varicella, unknown disease history",1 Dose,States,Arizona,2009-10,97.5,89287.0,93.9,NaN,NaN,Census
1157,"Varicella, unknown disease history",1 Dose,States,Arkansas,2009-10,98.3,34733.0,100.0,*,NaN,Census
1158,"Varicella, unknown disease history",1 Dose,States,California,2009-10,96.6,507191.0,100.0,*,NaN,Census